# Generated by Django 4.2.9 on 2024-02-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kakao',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'kakao',
            },
        ),
    ]
