# Generated by Django 5.0.1 on 2024-01-06 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('match_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('champions', models.TextField(max_length=30)),
                ('kills', models.TextField(max_length=30)),
                ('deaths', models.TextField(max_length=100)),
                ('assists', models.TextField(max_length=30)),
                ('results', models.TextField(max_length=30)),
                ('kda', models.TextField(max_length=30)),
                ('position', models.TextField(max_length=30)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
